### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by natxocc** [seanlandsman/ag-grid-vue-umd#1]
Is there any real UMD version that I can insert with?:
`<script src="http://cdn/aggridvue.umd.js">`

like a real UMD version?
It's not a real UMD as we need to code in *.js the code I need in this example.

Thanks

**Comment by mblackritter** [comment]
I'm wondering about the same, because not relying on any build tools is a requirement for my current project and the reason we chose Vue, and so far ag-Grid is the only solution not playing well. 😊

**Comment by mblackritter** [comment]
I was wondering about the very same last night, because not relying on any build tools is a requirement for a current project and the reason we chose Vue.

What @natxocc and I refer to is something like [vue-apexcharts.js](https://github.com/apexcharts/vue-apexcharts/blob/master/dist/vue-apexcharts.js) does, which can be loaded via ```<script/>``` and made available for use in your templates:
```javascript
Vue.component('apexchart', VueApexCharts)
```

Coming from [How to get single js file ag-grid + ag-grid-vue?](https://github.com/ag-grid/ag-grid-vue/issues/26#issuecomment-445181718), I expected to find a similar working solution, but found that it would instead need a build step, so I'm glad there's a solution, at least for the meantime. 😊

Get the latest versions of ag-Grid and ag-Grid-Vue:

```
yarn add ag-grid-community
yarn add ag-grid-vue
```

Copy the wanted files from node_modules/\*/dist/, so we're able to load them the way we want:

```html
  <link href="vendor/ag-grid/styles/ag-grid.css" rel="stylesheet" />
  <link href="vendor/ag-grid/styles/ag-theme-balham.css" rel="stylesheet" />
  
  <script src="vendor/ag-grid/ag-grid-community.min.noStyle.js"></script>
  <script src="vendor/ag-grid/ag-grid-vue.umd.js"></script>
```

As JS doesn't allow dashes in variable names, we've to adjust the UMD file:

Within ag-grid-vue.umd.js and ag-grid-vue.umd.min.js, replace the two occurances of ```["ag-grid-vue"]``` with ```["AgGridVue"]```.

Finally, in your single app.js, before you init your app with something like

```javascript
var app = new Vue({
```

make the ```AgGridVue``` component known to Vue as ```ag-grid-vue```:

```javascript
Vue.component('ag-grid-vue', AgGridVue.AgGridVue)
```

That's it. Now we can call ```<ag-grid-vue>``` within our templates:

```javascript
<ag-grid-vue class="ag-theme-balham"
             :column-defs="columnDefs"
             :row-data="rowData">
</ag-grid-vue>
```

Notice that we'd to replace ```columnDefs``` and ```rowData``` from the example ([AgGridApp.vue](https://github.com/seanlandsman/ag-grid-vue-umd/blob/master/AgGridApp.vue)) to ```column-defs``` and ```row-data```, as they lead to an empty grid ("Loading...") and Vue giving the following warnings:

```
[Warning] [Vue tip]: Prop "rowdata" is passed to component <Anonymous>, but the
declared prop name is "rowData". Note that HTML attributes are case-insensitive
and camelCased props need to use their kebab-case equivalents when using in-DOM
templates. You should probably use "row-data" instead of "rowData".

[Warning] [Vue tip]: Prop "columndefs" is passed to component <Anonymous>, but the
 declared prop name is "columnDefs". Note that HTML attributes are case-insensitive
 and camelCased props need to use their kebab-case equivalents when using in-DOM
 templates. You should probably use "column-defs" instead of "columnDefs".
```

> 😹💦 Just being happy about this quick work around.

**Comment by mblackritter** [comment]
I was wondering about the very same last night, because not relying on any build tools is a requirement for a current project and the reason we chose Vue.

What @natxocc and I refer to is something like [vue-apexcharts.js](https://github.com/apexcharts/vue-apexcharts/blob/master/dist/vue-apexcharts.js) does, which can be loaded via ```<script/>``` and made available for use in your templates:
```javascript
Vue.component('apexchart', VueApexCharts)
```

Coming from [How to get single js file ag-grid + ag-grid-vue?](https://github.com/ag-grid/ag-grid-vue/issues/26#issuecomment-445181718), I expected to find a similar working solution, but found that it would instead need a build step, so I'm glad there's a solution, at least for the meantime. 😊

Get the latest versions of ag-Grid and ag-Grid-Vue:

```
yarn add ag-grid-community
yarn add ag-grid-vue
```

Copy the wanted files from node_modules/\*/dist/, so we're able to load them the way we want:

```html
  <link href="vendor/ag-grid/styles/ag-grid.css" rel="stylesheet" />
  <link href="vendor/ag-grid/styles/ag-theme-balham.css" rel="stylesheet" />
  
  <script src="vendor/ag-grid/ag-grid-community.min.noStyle.js"></script>
  <script src="vendor/ag-grid/ag-grid-vue.umd.js"></script>
```

As JS doesn't allow dashes in variable names, we've to adjust the UMD file.

Within ag-grid-vue.umd.js and ag-grid-vue.umd.min.js, replace the two occurances of ```["ag-grid-vue"]``` with ```["AgGridVue"]```.

Finally, in your single app.js, before you init your app with something like

```javascript
var app = new Vue({
```

make the AgGridVue component known to Vue as ag-grid-vue:

```javascript
Vue.component('ag-grid-vue', AgGridVue.AgGridVue)
```

That's it. Now we can call ```<ag-grid-vue>``` within our templates.

```javascript
<ag-grid-vue style="height: 50vh"
             class="ag-theme-balham"
             :column-defs="columnDefs"
             :row-data="rowData">
</ag-grid-vue>
```

Notice that we'd to replace ```columnDefs``` and ```rowData``` from the example ([AgGridApp.vue](https://github.com/seanlandsman/ag-grid-vue-umd/blob/master/AgGridApp.vue)) to ```column-defs``` and ```row-data```, as they lead to an empty grid ("Loading...") and Vue giving the following warnings:

```
[Warning] [Vue tip]: Prop "rowdata" is passed to component <Anonymous>, but the
declared prop name is "rowData". Note that HTML attributes are case-insensitive
and camelCased props need to use their kebab-case equivalents when using in-DOM
templates. You should probably use "row-data" instead of "rowData".

[Warning] [Vue tip]: Prop "columndefs" is passed to component <Anonymous>, but the
 declared prop name is "columnDefs". Note that HTML attributes are case-insensitive
 and camelCased props need to use their kebab-case equivalents when using in-DOM
 templates. You should probably use "column-defs" instead of "columnDefs".
```

> 😹💦 Just being happy about this quick work around.

**Comment by natxocc** [comment]
Thanks @mblackritter !!!!
I didn't expect to modify anything to obtain results, but with your guide I find a working version with ag-grid with UMD.

**Comment by seanlandsman** [comment]
Please take a look at the latest state of this repo - I demonstrate how to run AG Grid and AG Grid Vue with plain JS straight from an HTML file.
